- name: variables
  hosts: local
  connection: local
  vars:
    PURPOSE: bounce back
    NAME: Sandeep
    Year: 2025
  tasks:
  - name: print the variable
    ansible.builtin.debug:
      msg: "{{ NAME }} will {{ PURPOSE }} in {{ Year }}"