- name: variables
  hosts: local
  connection: local
  vars: #Play level variables
    PURPOSE: bounce back
    NAME: Sandeep
    Year: 2025
  tasks:
  - name: print the variable
    vars: #task level variable
      PURPOSE: I'll be back
    ansible.builtin.debug:
      msg: "{{ NAME }} will {{ PURPOSE }} in {{ Year }}"
  
  - name: print the variable1
    ansible.builtin.debug:
      msg: "{{ NAME }} will {{ PURPOSE }} in {{ Year }}"