- name: variables from files
  hosts: local
  connection: local
  tasks:
  - name: print information
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }} duration is {{ DURATION }}, Learner is {{ LEARNER }}"
