- name: variables
  hosts: local
  connection: local
  vars: #Play level variables
    GREET: "From Play"
  vars_files:
  - vars.yml
  # vars_prompt:
  # - name: GREET
  #   prompt: Enter the value
  #   private: false
  tasks:
  - name: print the variable
    # vars:
    #   GREET: "TASK"
    ansible.builtin.debug:
      msg: "Hello from {{ GREET }}"

#1. Command line or ARGS
#2. Task level
#3. Prompt