- name: create ec2 and r53 records
  connection: local
  hosts: local
  vars:
    subnet_id: subnet-08df8cce9ddb080ec
    sg_id: sg-062c5cee10335e6cc
    ami_id: ami-09c813fb71547fc4f
    instance_type: t2.micro
    instances:
    - mysql
    - backend
    - frontend
  tasks:
  - name: create ec2 instances
    amazon.aws,ec2_instance:
      name: "{{ item }}"
      subnet_id: "{{ subnet_id }}"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      instance_type: "{{ instance_type }}"
    loop: "{{ instances }}"